### PR TITLE
Add an option for redirecting Rhombus Dungeon entrance to character selection map

### PR DESCRIPTION
**Pull request by krypciak**
It annoyed me so much that I did this.
The option name and description can be adjusted to your likings.
This could probably be done more gracefully with alybox, but I didn't want to introduce an unnecessary dependency.

_No Sergey I don't want to spoof my class_

### CODE REVIEW

**Review by XenonA7 — CHANGES_REQUESTED** [review]
Does it require restarting the game?
1. Launched the game, it was enabled by default. Start new game, enter the modded map like normal.
2. Return to title screen, disable the option. Start new game, still goes to modded map.
3. Reboot the game, the option is still disabled. Start new game, skips the modded map.

The other thing is line 19 in plugin.js says 'Xeons triblader mod', can this be changed to 'Triblader mod'?

This is a really advanced and impressive way to implement the option to skip the intro, nice work. I would like that menu header changed though, at least to fix the typo.

**Comment by krypciak** [comment]
I changed the header to `Triblader mod` and updated the description, now it says it needs a restart.

**Comment by krypciak** [comment]
I changed the header to Triblader mod and updated the description, now it says it needs a restart.

**Comment by XenonA7** [comment]
Trying https://github.com/XenonA7/xenons-triblader-mod/pull/9/commits/42bb2579c5c996e0a32cc04900f27ad4627db30f:
I am seeing this upon starting a new game with the option to redirect enabled:
image

Error doesn't happen when starting a new game after disabling the option (and restart). However, with it disabled, the patch is loaded and it redirects to the modded map.

Re-enabling the option and rebooting the game, then starting again reproduces the error in the screenshot above. Not sure what is going on here.
CCLoader 2.22.1
Crosscode 1.4.2-1

**Comment by krypciak** [comment]
I cannot reproduce this issue for the life of me.
I downgraded CC to your version and installed your version of ccloader, no success.
What mods do you have?

**Comment by XenonA7** [comment]
I figured it out, it is because the PR moves **dng-top.json.patch** from the **assets** directory to the **patches** directory. The way I structure my mod is for ".json.patch" files to be included in the assets directory, and for .json data files loaded with the INCLUDE patch step to go in the patches directory.

With this being a .patch file, I would like to keep it in the assets directory.

Although I just tried to put it in the assets directory and change the path in plugin.js, but it is loaded every time regardless of the option. I assume putting it in the patches directory was a requirement to make it work in the first place?

**Comment by krypciak** [comment]
If the patch is under `assets`, it will be always loaded by the modloader.
I conditionality spoof the location of the patch that is under the `patches` directory (which is not loaded automatically),
so the modloader thinks it's under `assets`.

**Comment by XenonA7** [comment]
Got it. I'm sorry for inconveniencing you earlier, I should have realized this. I will note that this one patch file needs to be kept in the separate directory for this feature to work.

I will close and merge this tomorrow after a final check with all other mods enabled again.

**Pull request merged**
